// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ResizeImageJobEx.DataApi.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Ad
    {
        /// <summary>
        /// Initializes a new instance of the Ad class.
        /// </summary>
        public Ad() { }

        /// <summary>
        /// Initializes a new instance of the Ad class.
        /// </summary>
        public Ad(long? id = default(long?), byte[] version = default(byte[]), long? categoryId = default(long?), string title = default(string), double? price = default(double?), string description = default(string), string imageUrl = default(string), string thumbnailUrl = default(string), string phone = default(string), DateTime? posted = default(DateTime?), DateTime? lastModified = default(DateTime?), Category category = default(Category))
        {
            Id = id;
            Version = version;
            CategoryId = categoryId;
            Title = title;
            Price = price;
            Description = description;
            ImageUrl = imageUrl;
            ThumbnailUrl = thumbnailUrl;
            Phone = phone;
            Posted = posted;
            LastModified = lastModified;
            Category = category;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public long? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Version")]
        public byte[] Version { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CategoryId")]
        public long? CategoryId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Title")]
        public string Title { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Price")]
        public double? Price { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Description")]
        public string Description { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Image_Url")]
        public string ImageUrl { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Thumbnail_Url")]
        public string ThumbnailUrl { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Phone")]
        public string Phone { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Posted")]
        public DateTime? Posted { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "LastModified")]
        public DateTime? LastModified { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Category")]
        public Category Category { get; set; }

    }
}
