//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ad
    {
        public long Id { get; set; }
        public byte[] Version { get; set; }
        public long CategoryId { get; set; }
        public string Title { get; set; }
        public decimal Price { get; set; }
        public string Description { get; set; }
        public string Image_Url { get; set; }
        public string Thumbnail_Url { get; set; }
        public string Phone { get; set; }
        public System.DateTime Posted { get; set; }
        public System.DateTime LastModified { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
